name: Google Driveへ同期

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v4

      - name: 圧縮ファイル作成
        run: zip -r repository.zip . -x "*.git*"

      - name: Google Driveへアップロード
        uses: adityak74/google-drive-upload-git-action@v0.3
        with:
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          filename: repository.zip
          folderId: ${{ secrets.GDRIVE_FOLDER_ID }}
          overwrite: true